### ISSUE TITLE
HatCHRy onboarding program

### ISSUE THREAD

**Issue by MikelThief** [karoldem/7segmentSPI#1]
-

**Comment by karoldem** [comment]
Thanks, application posted. My email is karoldem@gmail.com and is visible now, so feel free to contact.

**Comment by karoldem** [comment]
> Hi! On Saturday we met at WDI22 Job fair at the C.H. Robinson stand. I promised to review your projects - I like the effort you put into them. I would love to have you participate in the HatCHRy program, so please apply for this offer through our [website](https://jobs.chrobinson.com/job/warsaw/junior-software-engineer-net-start-date-1st-june/209/23625330448) or [JustJoin.it](https://justjoin.it/offers/c-h-robinson-junior-net-developer-5e8c351e-6af1-4383-91d9-7ce4a1f11457).
> 
> At the same time, I apologize to you for contacting you this way. Your Github profile is the only contact I took from you. Nevertheless, I keep my word and get back to you with feedback. Feel free to close/delete this issue if you no longer consider it valuable.
> 
> Looking forward to your submission! :)

Thanks, application posted. My email is [karoldem@gmail.com](mailto:karoldem@gmail.com) and is visible now, so feel free to contact
